version: '3'

services:
  db:
    image: mysql:5.7.25
  web:
    volumes:
      - .:/code
    command: "/venv/bin/python manage.py runserver 0.0.0.0:8000"
    build: 
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db    
    ports:
      - "8000:8000"
stdin_open: 'true'
tty: 'true'
