# Generated by Django 2.1.5 on 2019-02-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srpwebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='datetime_visit_was_scheduled',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
