# Generated by Django 2.1.5 on 2019-03-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srpwebapp', '0005_photo_upload_record'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Code',
            new_name='Gate',
        ),
        migrations.RenameField(
            model_name='gate',
            old_name='gate',
            new_name='gate_number',
        ),
    ]
