# Generated by Django 2.1.5 on 2019-04-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srpwebapp', '0010_auto_20190330_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=60)),
                ('upload_datetime', models.DateTimeField()),
                ('img_name', models.CharField(max_length=60)),
            ],
        ),
    ]
