# Generated by Django 2.1.5 on 2019-04-12 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srpwebapp', '0011_uploaded_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded_image',
            old_name='img_name',
            new_name='img_path',
        ),
    ]
