# Generated by Django 2.1.5 on 2019-04-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srpwebapp', '0013_auto_20190412_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
