# Generated by Django 2.1.5 on 2019-04-23 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srpwebapp', '0015_auto_20190423_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo_upload_record',
            name='user',
        ),
        migrations.DeleteModel(
            name='Photo_Upload_Record',
        ),
    ]
