# Generated by Django 2.1.5 on 2019-04-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srpwebapp', '0016_auto_20190423_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploaded_image',
            name='caption',
            field=models.TextField(default=''),
        ),
    ]
