# Generated by Django 2.1.5 on 2019-04-29 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srpwebapp', '0017_uploaded_image_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='time_created',
            field=models.DateField(null=True),
        ),
    ]
