# Generated by Django 2.1.5 on 2019-05-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srpwebapp', '0018_auto_20190429_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gate',
            name='gate_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gate',
            name='lock_code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
